on: push
name: rust

env:
    RUSTFLAGS: "-Dwarnings"

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: checkout codebase
              uses: actions/checkout@v3

            - name: install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: cache
              uses: Swatinem/rust-cache@v2

            - name: test
              run: cargo test

            - name: clippy
              run: cargo clippy --all-targets --all-features -- -D warnings
