//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "field")]
pub enum Field {
    #[sea_orm(string_value = "Title")]
    Title,
    #[sea_orm(string_value = "Description")]
    Description,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "operation")]
pub enum Operation {
    #[sea_orm(string_value = "Is")]
    Is,
    #[sea_orm(string_value = "IsNot")]
    IsNot,
    #[sea_orm(string_value = "Contains")]
    Contains,
    #[sea_orm(string_value = "DoesNotContain")]
    DoesNotContain,
    #[sea_orm(string_value = "RegularExpression")]
    RegularExpression,
}
